# Generated by Django 4.0.6 on 2022-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_create_date_item_last_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('l', 'Lost'), ('f', 'Found')], max_length=1),
        ),
    ]
