# Generated by Django 4.0.6 on 2022-07-27 17:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Enter e-mail', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number', max_length=128, region='BY', unique=True),
        ),
    ]
