# Generated by Django 4.0.6 on 2022-08-01 19:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_item_who_found_alter_item_who_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Category name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='E-mail', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(help_text='Last name', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('l', 'lost'), ('f', 'found')], default='f', help_text='Item type', max_length=1),
        ),
    ]
